apiVersion: v1
kind: ConfigMap
metadata:
  name: multi-cluster-nginx
  namespace: {{ .Values.namespace }}
data:
  nginx.conf: |
    worker_processes  auto;

    error_log  /var/log/nginx/error.log notice;
    pid        /tmp/nginx.pid;


    events {
        worker_connections  1024;
    }

    http {
        proxy_temp_path /tmp/proxy_temp;
        client_body_temp_path /tmp/client_temp;
        fastcgi_temp_path /tmp/fastcgi_temp;
        uwsgi_temp_path /tmp/uwsgi_temp;
        scgi_temp_path /tmp/scgi_temp;
      
        include       /etc/nginx/mime.types;
        default_type  application/octet-stream;

        log_format  main  '$remote_addr - $remote_user [$time_local] "$request" '
                          '$status $body_bytes_sent "$http_referer" '
                          '"$http_user_agent" "$http_x_forwarded_for"';

        access_log  /var/log/nginx/access.log  main;

        sendfile        on;
        #tcp_nopush     on;

        keepalive_timeout  65;

        #gzip  on;

        server {
            listen 8080 default_server;
            root /usr/share/nginx/html/;
            index index.html index.htm;

            location / {
                try_files $uri /index.html;
            }

            location ~* ^/multicluster/.*\.(js|cjs|mjs)$ {
                default_type text/javascript;
                rewrite ^ /dist/multicluster.mjs break;
            }

            location ~* \.(js|cjs|mjs)$ {
                default_type text/javascript;
                rewrite ^ /dist/multicluster.mjs break;
            }

            {{ if .Values.backend }}
            location /rest/multicluster {
                proxy_ssl_verify off;
                proxy_ssl_trusted_certificate /etc/nginx/cert/ca.crt;
                proxy_pass {{ .Values.backend }}:{{ .Values.service.backendPort }};
            }
            {{ end }}
        }
    }
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: ca
  namespace: {{ .Values.namespace }}
data:
  ca.crt: |
    -----BEGIN CERTIFICATE-----
    MIIDsTCCApmgAwIBAgIUX8BbAh/bTr6nzg3LPd1dtcJK7uIwDQYJKoZIhvcNAQEL
    BQAwZzELMAkGA1UEBhMCY24xEDAOBgNVBAgMB2JlaWppbmcxEDAOBgNVBAcMB2Jl
    aWppbmcxDzANBgNVBAoMBmh1YXdlaTEOMAwGA1UECwwFc3BhcmsxEzARBgNVBAMM
    CmNvbG9jYXRpb24wIBcNMjQwODE3MDIwMjIyWhgPMjA1MjAxMDMwMjAyMjJaMGcx
    CzAJBgNVBAYTAmNuMRAwDgYDVQQIDAdiZWlqaW5nMRAwDgYDVQQHDAdiZWlqaW5n
    MQ8wDQYDVQQKDAZodWF3ZWkxDjAMBgNVBAsMBXNwYXJrMRMwEQYDVQQDDApjb2xv
    Y2F0aW9uMIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEA5phpkUnRXmXP
    UeRa1nnNkJhGV8l0r90EzgMZfAK+JlqjO5dd5GPukcK++Y5+T30hTQDWPMOBAjEf
    j9ESuD+RJ1ANIx+0rV7pu94n+Z9E32beWhnFQ9MR/HHV1K9LHZQKW9Dvv73k4viu
    NmHIeJPgxc3L8Nwlog6/ycYnoc0yt95/PnQg3NW/5M+CBWgGFsaVLkEGpDi950S0
    fAM8MtAY+wwdAbHd9lv6l7RfXzjCdUUWCvOD/Gi74+ay8m21sPElEb4OeJ9rfTJU
    6r8zSRTSaSrNznUpAaFkPFBKdgV6Ih8AZGQEUAm1gE8oLA5EBJ0Qt9+xElqfyqku
    fuko5X0MnwIDAQABo1MwUTAdBgNVHQ4EFgQU/Dc17HgYVpeCyBi8WLryZv2iqQEw
    HwYDVR0jBBgwFoAU/Dc17HgYVpeCyBi8WLryZv2iqQEwDwYDVR0TAQH/BAUwAwEB
    /zANBgkqhkiG9w0BAQsFAAOCAQEAoESclDBXMC4jcP5cFjTxUlOLSi/AovpsoaYr
    KLanLklEX/jNBuD/BzA4BBnqV6BQkcns5znMQS1EKxAABoawC8iRqZG4qL1HD9gU
    YnEBarWF2vUeaSuxcP6P0Qm0WS1vLaXt11yi7bIUTXv8/WpCdBZNXIGnIyMJ/uV+
    1+cGw7NI9pbm996EZ+ynWwtmzgQgUZf2ldu5dhCjj8HYh5S12BId2VephQiexzpS
    PQrr5Vh/u170O0k4geBXKJxC68yZQ8lwWNTurLrIPAfNYI4hHzBHwE9BKMZxN0yY
    AC+xnBuAVeIfkwMsh9Jof2TdTOcYCywA1iT1MzlO0asywDuSMw==
    -----END CERTIFICATE-----
